/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package trabalhofinal;

import Main.EstoqueLivro;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 55899
 */
public class ProcurarLivro extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProcurarLivro
     */
    public ProcurarLivro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tituloLivro = new javax.swing.JTextField();
        buttonProcurar = new javax.swing.JButton();
        showTitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaProcura = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel1.setText("Titulo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 40, 31, 16);
        jPanel1.add(tituloLivro);
        tituloLivro.setBounds(10, 70, 218, 24);

        buttonProcurar.setBackground(new java.awt.Color(102, 255, 204));
        buttonProcurar.setText("Procurar Livro");
        buttonProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProcurarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonProcurar);
        buttonProcurar.setBounds(340, 130, 112, 32);

        showTitulo.setFont(new java.awt.Font("Dubai", 3, 18)); // NOI18N
        showTitulo.setText("Nome");
        jPanel1.add(showTitulo);
        showTitulo.setBounds(40, 140, 160, 32);

        tabelaProcura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Autor", "Genero", "Edicão", "Editora", "lingua", "Quantidade ", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaProcura);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 200, 530, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProcurarActionPerformed
        String titulo = tituloLivro.getText();
        int indice = EstoqueLivro.procurar(title);
        
        if(indice == -1){
            JOptionPane.showMessageDialog(null, "Livro não encontrado");
        }else{
            showTitulo.setText(titulo);
            
            DefaultTableModel dmProdutos = (DefaultTableModel) tabelaProcura.getModel();
            String autor = EstoqueLivro.mostrar(indice, 0);
            String genero = EstoqueLivro.mostrar(indice, 1);
            String edicao = EstoqueLivro.mostrar(indice, 2);
            String editora = EstoqueLivro.mostrar(indice, 3);
            String lingua = EstoqueLivro.mostrar(indice, 4);
            int quantidade = Integer.parseInt(EstoqueLivro.mostrar(indice, 5));
            double preco = Double.parseDouble(EstoqueLivro.mostrar(indice, 6));
            
           Object[] dados = {autor,genero,edicao,editora,lingua,quantidade,preco};
           dmProdutos.addRow(dados);
            
        }
    }//GEN-LAST:event_buttonProcurarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonProcurar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel showTitulo;
    private javax.swing.JTable tabelaProcura;
    private javax.swing.JTextField tituloLivro;
    // End of variables declaration//GEN-END:variables
}
