/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package trabalhofinal;

/**
 *
 * @author 55899
 */
public class Sobre extends javax.swing.JInternalFrame {

    /**
     * Creates new form Sobre
     */
    public Sobre() {
        initComponents();
        jLabel10.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jPanel1.setLayout(null);

        jLabel1.setText("\"Este é um projeto elaborado e arquitetado por Cintia Teixeira e Marcos Brito. ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 441, 16);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(6, 128, 0, 0);

        jLabel3.setText("O programa foi desenvolvido com todo o aprendizado obtido em sala de aula,");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 40, 434, 16);

        jLabel4.setText("com o intuito de apresentar a consolidação dos nossos conhecimentos em java.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 60, 455, 16);

        jLabel5.setText("O programa criado trata-se de uma simulação de um sistema bibliotecário que,");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 80, 449, 16);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(460, 116, 0, 0);

        jLabel7.setText("com exceção, de banco de dados, poossui os principais implementos que um ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 100, 442, 16);

        jLabel8.setText("sistema desse gênero necessita.\"");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 120, 195, 16);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/foto minha.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 140, 510, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
